export default {
  FETCH_STARTER: 'STARTER',
  FETCH_ROOM: 'FETCH_ROOM',
  ROOM_CHANGE: 'ROOM_CHANGE',
  MESSAGE_CREATED: 'MESSAGE_CREATED',
  MESSAGE_FETCHED: 'MESSAGE_FETCHED',
  AUTH_TOKEN_RECIEVED: 'AUTH_TOKEN_RECIEVED',
}
